# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
    build:
        machine:
            image: circleci/classic:201808-01

        working_directory: ~/repo

        steps:
          - checkout

          - run:
              name: Build docker images
              command: |
                GIT_COMMIT=$(git rev-parse HEAD)
                echo "Building base publisher docker image ..."
                docker build --target base -t kidsfirstdrc/fhir-ig-publisher:latest -t kidsfirstdrc/fhir-ig-publisher:$GIT_COMMIT  .
                echo "Building circleci publisher docker image ..."
                docker build --target circleci -t kidsfirstdrc/fhir-ig-publisher:circleci .

          - run:
              name: Run publisher integration test
              command: ./scripts/test.sh

          - run:
              name: 'Push docker images to DockerHub'
              command: |
                  if [ $CIRCLE_BRANCH == 'master' ]; then
                    docker login -u kidsfirstdrc -p $KF_DOCKER_HUB_PW
                    docker push kidsfirstdrc/fhir-ig-publisher:latest
                    docker push kidsfirstdrc/fhir-ig-publisher:$GIT_COMMIT
                    docker push kidsfirstdrc/fhir-ig-publisher:circleci
                  fi
