# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
    build:
        machine:
            image: circleci/classic:201808-01

        working_directory: ~/repo

        steps:
          - checkout

          - run:
              name: Build publisher docker image
              command: docker build -t kidsfirstdrc/fhir-ig-publisher:latest .

          - run:
              name: Run publisher integration test
              command: ./scripts/test.sh

          - run:
              name: 'Push publisher docker image to DockerHub'
              command: |
                if [ $CIRCLE_BRANCH == 'master' ]; then
                    GIT_COMMIT=$(git rev-parse HEAD)
                    VERSION=$(cat version.json | jq -r '.publisher.version')
                    docker login -u kidsfirstdrc -p $KF_DOCKER_HUB_PW
                    docker tag kidsfirstdrc/fhir-ig-publisher:latest kidsfirstdrc/fhir-ig-publisher:$GIT_COMMIT
                    docker tag kidsfirstdrc/fhir-ig-publisher:latest kidsfirstdrc/fhir-ig-publisher:$VERSION
                    docker push kidsfirstdrc/fhir-ig-publisher:latest
                    docker push kidsfirstdrc/fhir-ig-publisher:$GIT_COMMIT
                    docker push kidsfirstdrc/fhir-ig-publisher:$VERSION
                fi
